# Generated by Django 3.2.4 on 2021-07-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20210703_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
