# Generated by Django 3.2.4 on 2021-07-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_review_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='bookImages'),
        ),
    ]
